// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import AutosaveController from './autosave_controller'
Stimulus.register('autosave', AutosaveController)

import Bridge__FormController from './bridge/form_controller'
Stimulus.register('bridge--form', Bridge__FormController)

import Bridge__ToastController from './bridge/toast_controller'
Stimulus.register('bridge--toast', Bridge__ToastController)

import FlashController from './flash_controller'
Stimulus.register('flash', FlashController)

import HelloController from './hello_controller'
Stimulus.register('hello', HelloController)

import PasswordRevealController from './password_reveal_controller'
Stimulus.register('password-reveal', PasswordRevealController)

import SidebarController from './sidebar_controller'
Stimulus.register('sidebar', SidebarController)

import ThemeController from './theme_controller'
Stimulus.register('theme', ThemeController)

import TurboSelectController from './turbo_select_controller'
Stimulus.register('turbo-select', TurboSelectController)